// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/schemaForm/registerComponents":{"path":"schema-form/register-components","id":"docs/schemaForm/registerComponents","parentId":"DocLayout"},"docs/schemaForm/groupSchema":{"path":"schema-form/group-schema","id":"docs/schemaForm/groupSchema","parentId":"DocLayout"},"docs/schemaForm/performance":{"path":"schema-form/performance","id":"docs/schemaForm/performance","parentId":"DocLayout"},"docs/schemaForm/remoteData":{"path":"schema-form/remote-data","id":"docs/schemaForm/remoteData","parentId":"DocLayout"},"docs/schemaForm/linkage":{"path":"schema-form/linkage","id":"docs/schemaForm/linkage","parentId":"DocLayout"},"docs/schemaForm/readme":{"path":"schema-form/readme","id":"docs/schemaForm/readme","parentId":"DocLayout"},"docs/schemaForm/basic":{"path":"schema-form/basic","id":"docs/schemaForm/basic","parentId":"DocLayout"},"docs/github":{"path":"github","id":"docs/github","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "dumi__pages__404" */'@/dumi__pages/404')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__ContextWrapper" */'@/dumi__theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__layouts__DocLayout" */'@/dumi__theme/layouts/DocLayout')),
'docs/schemaForm/registerComponents': React.lazy(() => import(/* webpackChunkName: "docs__schemaForm__registerComponents.md" */'/Users/cxd/Documents/my-lib/antd-pro/docs/schemaForm/registerComponents.md')),
'docs/schemaForm/groupSchema': React.lazy(() => import(/* webpackChunkName: "docs__schemaForm__groupSchema.md" */'/Users/cxd/Documents/my-lib/antd-pro/docs/schemaForm/groupSchema.md')),
'docs/schemaForm/performance': React.lazy(() => import(/* webpackChunkName: "docs__schemaForm__performance.md" */'/Users/cxd/Documents/my-lib/antd-pro/docs/schemaForm/performance.md')),
'docs/schemaForm/remoteData': React.lazy(() => import(/* webpackChunkName: "docs__schemaForm__remoteData.md" */'/Users/cxd/Documents/my-lib/antd-pro/docs/schemaForm/remoteData.md')),
'docs/schemaForm/linkage': React.lazy(() => import(/* webpackChunkName: "docs__schemaForm__linkage.md" */'/Users/cxd/Documents/my-lib/antd-pro/docs/schemaForm/linkage.md')),
'docs/schemaForm/readme': React.lazy(() => import(/* webpackChunkName: "docs__schemaForm__readme.md" */'/Users/cxd/Documents/my-lib/antd-pro/docs/schemaForm/readme.md')),
'docs/schemaForm/basic': React.lazy(() => import(/* webpackChunkName: "docs__schemaForm__basic.md" */'/Users/cxd/Documents/my-lib/antd-pro/docs/schemaForm/basic.md')),
'docs/github': React.lazy(() => import(/* webpackChunkName: "docs__github.md" */'/Users/cxd/Documents/my-lib/antd-pro/docs/github.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/cxd/Documents/my-lib/antd-pro/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "dumi__pages__Demo" */'@/dumi__pages/Demo')),
},
  };
}
