// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/cxd/Documents/my-lib/antd-pro/node_modules/.pnpm/dumi@2.2.1_c32rawj2nx44oeqssekbnwqmc4/node_modules/dumi/theme-default/slots/SearchResult/index.js';
